language: java
dist: trusty
cache:
  directories:
  - $HOME/.m2
services:
  - mysql
jdk:
  - oraclejdk8
sudo: required
addons:
  apt: 
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
install: travis_wait git clone https://github.com/gchq/event-logging.git && cd event-logging && mvn -q clean install && cd ../ && rm -rf event-logging
script: mvn install -DSTROOM_JDBC_USERNAME=root -DSTROOM_JDBC_DRIVER_URL=jdbc:mysql://127.0.0.1/stroom?useUnicode=yes&characterEncoding=UTF-8

