language: java
cache:
  directories:
  - $HOME/.m2
services:
  - mysql
jdk:
  - oraclejdk8
sudo: false
install: travis_wait git clone https://github.com/gchq/event-logging.git && cd event-logging && mvn -q clean install && cd ../ && rm -rf event-logging
script: mvn install
